"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function PlayerRegistrationForm({ token }: { token: string }) {
  const router = useRouter(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/registration-invites/accept", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...data, token, consent: data.consent === "on" }) }); const body = await response.json().catch(() => null); if (!response.ok) { setError(body?.detail ?? "This invite could not be accepted"); setSaving(false); return; } router.push("/dashboard"); }
  return <main className="flex min-h-dvh items-center justify-center bg-background px-5 py-10"><section className="panel w-full max-w-lg p-8"><p className="text-xs font-medium tracking-widest text-muted">FINAL THIRD CLUBHOUSE</p><h1 className="mt-3 text-3xl font-medium tracking-tight">Complete player registration</h1><p className="mt-2 text-sm leading-relaxed text-muted">Create your parent account and confirm the player’s details.</p><form className="mt-7 grid gap-4" onSubmit={submit}><div className="grid grid-cols-2 gap-4"><input name="legal_first_name" placeholder="First name" className="rounded-lg border border-line bg-surface-muted px-3 py-3 text-sm" required /><input name="legal_last_name" placeholder="Last name" className="rounded-lg border border-line bg-surface-muted px-3 py-3 text-sm" required /></div><input name="email" type="email" placeholder="Parent email" className="rounded-lg border border-line bg-surface-muted px-3 py-3 text-sm" required /><input name="password" type="password" minLength={8} placeholder="Create password" className="rounded-lg border border-line bg-surface-muted px-3 py-3 text-sm" required /><label className="grid gap-2 text-sm">Date of birth<input name="date_of_birth" type="date" className="rounded-lg border border-line bg-surface-muted px-3 py-3" required /></label><input name="fa_fan_id" placeholder="FA FAN ID (optional)" className="rounded-lg border border-line bg-surface-muted px-3 py-3 text-sm" /><label className="flex items-start gap-3 text-sm"><input name="consent" type="checkbox" className="mt-1" required />I confirm these details and give consent for this registration.</label>{error && <p className="rounded-lg bg-danger-soft px-3 py-2 text-sm text-danger">{error}</p>}<button className="button-primary rounded-lg px-4 py-3 text-sm" disabled={saving || !token}>{saving ? "Completing registration…" : "Complete registration"}</button></form></section></main>;
}
