import { PageHeading } from "@/components/page-ui";
import { SafeguardingContactSettings } from "@/components/safeguarding-contact-settings";
import { getAuthenticatedApiUser } from "@/lib/auth";
import { getPublicClub } from "@/lib/public-club";

export const metadata = { title: "Safeguarding" };

export default async function SafeguardingPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const { club, safeguarding } = await getPublicClub();
  const user = await getAuthenticatedApiUser();
  const membership = user?.memberships.find((item) => item.club_id === club.id);
  const canEdit = membership?.role === "owner" || membership?.role === "admin";
  const { edit } = await searchParams;
  return <><PageHeading eyebrow="SAFEGUARDING" title="Keeping our club safe" description={`${club.name} is committed to providing a safe, positive environment for every child and young person.`} /><div className="grid gap-4">{canEdit && edit === "1" ? <SafeguardingContactSettings initial={safeguarding} /> : null}<section className="panel border-l-4 border-accent p-6"><h2 className="text-lg font-medium">Report a concern</h2><p className="mt-3 text-sm leading-relaxed text-muted">If you are worried about a child or an adult’s behaviour towards a child, report it without delay. Contact our Club Welfare Officer or The FA Safeguarding Team. If someone is in immediate danger, contact the Police or Children’s Social Care.</p><div className="mt-5 grid gap-2 text-sm">{safeguarding.contact_name ? <p><strong>Club Welfare Officer:</strong> {safeguarding.contact_name}</p> : null}{safeguarding.contact_email ? <p><strong>Email:</strong> <a className="text-accent hover:underline" href={`mailto:${safeguarding.contact_email}`}>{safeguarding.contact_email}</a></p> : null}{safeguarding.contact_phone ? <p><strong>Phone:</strong> <a className="text-accent hover:underline" href={`tel:${safeguarding.contact_phone}`}>{safeguarding.contact_phone}</a></p> : null}<p><strong>The FA:</strong> <a className="text-accent hover:underline" href="mailto:safeguarding@thefa.com">safeguarding@thefa.com</a> · 0800 169 1863</p><p><strong>NSPCC:</strong> 0808 800 5000</p></div></section><section><h2 className="mb-3 text-lg font-medium">Our safeguarding documents</h2><div className="grid gap-3">{safeguarding.documents.map((document) => <a className="panel flex items-center justify-between gap-4 p-5 hover:border-accent" href={document.download_url} key={document.document_id}><span><span className="block text-xs font-medium uppercase tracking-wider text-muted">{document.category}</span><strong className="mt-1 block text-sm">{document.title}</strong></span><span className="text-xs text-accent">Download ↗</span></a>)}{safeguarding.documents.length === 0 ? <p className="panel p-6 text-sm text-muted">Safeguarding documents will be published here soon.</p> : null}</div></section><section className="panel p-6"><h2 className="text-lg font-medium">Other concerns and complaints</h2><p className="mt-3 text-sm leading-relaxed text-muted">Player registration, team selection and playing time are normally club operational matters. Please use our <a className="text-accent hover:underline" href="/contact">contact page</a> for those issues. Concerns about how a safeguarding matter was handled should follow the club’s complaints process before escalation.</p></section></div></>;
}
