"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function SafeguardingContactSettings({ initial }: { initial: { contact_name: string | null; contact_email: string | null; contact_phone: string | null } }) {
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const router = useRouter();
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/dashboard/safeguarding", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), phone: form.get("phone") }) }); const result = await response.json().catch(() => null); setSaving(false); setMessage(response.ok ? "Safeguarding contact saved." : result?.detail ?? "Could not save contact."); if (response.ok) router.refresh(); }
  return <form className="panel grid gap-4 p-6" onSubmit={save}><div><h2 className="text-base font-medium">Safeguarding contact</h2><p className="mt-1 text-sm leading-relaxed text-muted">These details appear on the public safeguarding page.</p></div><div className="grid grid-cols-3 gap-3 max-md:grid-cols-1"><input name="name" defaultValue={initial.contact_name ?? ""} placeholder="Club Welfare Officer name" className="rounded-lg border border-line bg-surface-muted px-3 py-2 text-sm" /><input name="email" type="email" defaultValue={initial.contact_email ?? ""} placeholder="Safeguarding email" className="rounded-lg border border-line bg-surface-muted px-3 py-2 text-sm" /><input name="phone" defaultValue={initial.contact_phone ?? ""} placeholder="Safeguarding phone" className="rounded-lg border border-line bg-surface-muted px-3 py-2 text-sm" /></div><button className="button-primary w-fit rounded-lg px-4 py-2 text-sm" disabled={saving}>{saving ? "Saving…" : "Save contact details"}</button>{message ? <p className="text-xs text-muted" role="status">{message}</p> : null}</form>;
}
